SN_Django/django_movie/django_movie/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("movies.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('contact/', include("contact.urls")),
    path('accounts/', include("allauth.urls")),
]

# urlpatterns += i18n_patterns(
#     path('pages/', include('django.contrib.flatpages.urls')),
#     path('contact/', include("contact.urls")),
#     path("", include("movies.urls")),
# )



if settings.DEBUG:
    # Django передает файлы из директории media при включенном debug
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SN_Django/django_movie/movies/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("", views.MovieView.as_view(), name="list_movie"),
    path("filter/", views.FilterMoviesView.as_view(), name='filter'),
    path("search/", views.Search.as_view(), name="search"),
    path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),
    path("json-filter/", views.JsonFilterMoviesView.as_view(), name='json_filter'),
    path("<slug:slug>/", views.MovieDetailView.as_view(), name="detail_movie"),
    path("review/<int:pk>/", views.AddReview.as_view(), name="add_review"),
    path("<slug:slug>/gallery/", views.MovieGallery.as_view(), name="gallery"),
    path("actor/<str:slug>/", views.ActorView.as_view(), name="actor_detail")
]

SN_Django/django_movie/movies/models.py
from datetime import date
from django.db import models

# Create your models here.
from django.urls import reverse
from django.db.models import Avg


class Category(models.Model):
    """Категории"""
    name = models.CharField("Категория", max_length=150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Actor(models.Model):
    """Актеры и режиссеры"""
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="actors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Актеры и режиссеры"
        verbose_name_plural = "Актеры и режиссеры"


class Genre(models.Model):
    """Жанры"""
    name = models.CharField("Имя", max_length=100)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Movie(models.Model):
    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Описание")
    trailer_url = models.CharField("Трейлер фильма", max_length=200, default='')
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Год выхода", default=2020)
    country = models.CharField("Страна", max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name="режиссер", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="актер", related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="жанры")
    world_premiere = models.DateField("Премьера в мире", default=date.today)
    runtime = models.PositiveSmallIntegerField("Продолжительность", default=0)
    budget = models.PositiveIntegerField("Бюджет", default=0, help_text="Указывать сумму в долларах")
    fees_in_usa = models.PositiveIntegerField(
        "Сборы в США", default=0, help_text="Указывать сумму в долларах"
    )
    fees_in_world = models.PositiveIntegerField(
        "Сборы в мире", default=0, help_text="Указывать сумму в долларах"
    )
    category = models.ForeignKey(
        Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True
    )
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("detail_movie", kwargs={"slug": self.url})

    def get_absolute_url_gallery(self):
        return reverse("gallery", kwargs={"slug": self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    def get_average_rating(self):
        return Rating.objects.filter(movie__title=self.title).aggregate(Avg('star')).get("star__avg")

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"


class MovieShots(models.Model):
    """Кадры из фильма"""
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"


class RatingStar(models.Model):
    """Звезд рейтинга"""
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="Звезда")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="Фильм")

    def __str__(self):
        return f'{self.star} - {self.movie}'

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True
    )
    movie = models.ForeignKey(Movie, verbose_name="фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

SN_Django/django_movie/movies/forms.py
from django import forms
from django.forms import RadioSelect
from snowpenguin.django.recaptcha3.fields import ReCaptchaField


from .models import Reviews, RatingStar, Rating

# форма на основе класса
class ReviewForm(forms.ModelForm):
    """Форма отзывов"""
    captcha = ReCaptchaField()


    class Meta:
        model = Reviews
        fields = ("name", "email", "text")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Ваше имя"}),
            "email": forms.EmailInput(attrs={"class": "form-control border", "placeholder": "Ваш Email"}),
            "text": forms.Textarea(attrs={"class": "form-control border"})
        }


class RatingForm(forms.ModelForm):
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)

SN_Django/django_movie/movies/views.py
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render


# Create your views here.
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.views.generic import ListView, DetailView

from movies.models import Movie, Actor, Genre, Rating
from .forms import ReviewForm, RatingForm


class GenreYearRating:
    """"""

    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movie.objects.filter(draft=False).values("year")


class MovieView(GenreYearRating, ListView):
    """Список фильмов"""
    # # Метод принимает get запросы
    # def get(self, request):
    #     movies = Movie.objects.all()
    #     return render(request, "movies/list_movie.html", {"movie_list": movies})
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    template_name = "movies/list_movie.html"
    paginate_by = 1


class MovieDetailView(GenreYearRating, DetailView):
    """ Полное описание фильма """
    # def get(self, request, slug):
    #     movie = Movie.objects.get(url=slug)
    #     return render(request, "movies/movie_detail.html", {"movie": movie})
    model = Movie

    # по какому полю следует искать запись
    slug_field = "url"
    template_name = "movies/detail_movie.html"

    def get_context_data(self, **kwargs):
        # словарь
        context = super().get_context_data(**kwargs)
        # добавление ключа и присваивание ему значения
        context["star_form"] = RatingForm()
        context["form"] = ReviewForm()
        return context


class MovieGallery(GenreYearRating, DetailView):
    """ Полное описание фильма """
    # def get(self, request, slug):
    #     movie = Movie.objects.get(url=slug)
    #     return render(request, "movies/movie_detail.html", {"movie": movie})
    model = Movie
    slug_field = "url"
    template_name = "movies/gallery.html"


# Класс для отправки отзывов
class AddReview(View):
    """Отзывы"""

    def post(self, request, pk):
        # передача и заполнение данных из post запроса
        form = ReviewForm(request.POST)
        # делаем запрос в бд на получение объекта по id
        movie = Movie.objects.get(id=pk)
        # проверка формы на валидность
        if form.is_valid():
            # указываем к какому фильму привязать отзыв
            # сначало приостанавливаем сохр формы
            form = form.save(commit=False)
            # если в POST запросе есть ключ parent (name у тега input),
            # то есть это ответ на отзыв,
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            # обращаемся к полю movie(в модели Reviews это внешний ключ)
            # для завязки фильма и отзыва
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())


class ActorView(GenreYearRating, DetailView):
    model = Actor
    template_name = "movies/actor.html"
    slug_field = "name"


class FilterMoviesView(GenreYearRating, ListView):
    template_name = "movies/list_movie.html"
    paginate_by = 1

    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre"))
        ).distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["year"] = ''.join([f'year={x}&' for x in self.request.GET.getlist("year")])
        context["genre"] = ''.join([f'genre={x}&' for x in self.request.GET.getlist("genre")])
        return context


class JsonFilterMoviesView(ListView):
    template_name = "movies/list_movie.html"

    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre"))
        ).distinct().values("title", "poster", "runtime", "url", "year", "genres__name")
        print(queryset)
        return queryset

    def get(self, request, *args, **kwargs):
        queryset = list(self.get_queryset())
        return JsonResponse({"movies": queryset}, safe=False)


class AddStarRating(View):
    """"Добавление рейтинга к фильму"""

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class Search(ListView):
    """Поиск фильмов"""
    paginate_by = 1
    template_name = "movies/list_movie.html"

    def get_queryset(self):
        return Movie.objects.filter(title__contains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'
        return context

SN_Django/django_movie/templates/movies/actor.html
{% extends 'movies/base.html' %}
{% block title %} {{ movie.title }} {% endblock title %}
  {% block movie %}
    <div class="container_film_header">
            <div class="container_film_header_text">Информация об актере</div>
    </div>
    <div class="container_films">
            <div class="container_film_item">
              <div class="container_film_item_inner">
                <div class="container_film_img_and_info">
                  <div class="container_film_img actor">
                        <img src="{{actor.image.url}}">
                  </div>
                  <div class="container_film_info">
                    <div class="container_film_info_inner">
                      <div class="container_film_about">
                        <div class="container_film_about_inner">
                          <div class="container_film_about_name">
                            <div class="container_film_about_name_text">
                              {{ actor.name }}
                            </div>
                          </div>
                          <div class="container_film_about_item">
                            <div class="container_film_about_item_spec">
                              Дата рождения
                            </div>
                            <div class="container_film_about_item_value">
                               {{ actor.age }} лет
                            </div>
                            <hr />
                          </div>
                          <div class="container_film_about_item">
                            <div class="container_film_about_item_spec">
                              Место рождения
                            </div>
                            <div class="container_film_about_item_value">
                                --------
                            </div>
                            <hr />
                          </div>
                          <div class="container_film_about_item">
                            <div class="container_film_about_item_spec">
                              Рост
                            </div>
                            <div class="container_film_about_item_value">
                                -------
                            </div>
                            <hr />
                          </div>
                          <div class="container_film_about_item">
                            <div class="container_film_about_item_spec">
                              Карьера
                            </div>
                            <div class="container_film_about_item_value">
                                --------
                            </div>
                            <hr />
                          </div>
                          <div class="container_film_about_item">
                            <div class="container_film_about_item_spec">
                              Награды
                            </div>
                            <div class="container_film_about_item_value">
                               -------
                            </div>
                            <hr />
                          </div>
                          <div class="container_film_about_item">
                            <div class="container_film_about_item_spec">
                              Жанры
                            </div>
                            <div class="container_film_about_item_value">
                               -------
                            </div>
                            <hr />
                          </div>
                          <div class="container_film_about_item">
                            <div class="container_film_about_item_spec">
                              Фильмы
                            </div>
                            <div class="container_film_about_item_value">
                               {% if actor.film_actor.all and actor.film_director.all%}
                                    {% for movie in actor.film_actor.all %}
                                        <a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a>
                                    {% endfor %}
                                    {% for movie in actor.film_director.all %}
                                        <a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a>
                                    {% endfor %}
                                {% elif actor.film_actor.all %}
                                    {% for movie in actor.film_actor.all %}
                                        <a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a>
                                    {% endfor %}
                                {% elif actor.film_director.all %}
                                    {% for movie in actor.film_director.all %}
                                        <a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <hr />
                          </div>
                          <div class="container_film_about_item">
                            <div class="container_film_about_item_spec">
                              Всего фильмов
                            </div>
                            <div class="container_film_about_item_value">
                               -------
                            </div>
                            <hr />
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="container_film_description">
                  <div class="container_film_description_text">
                    {{ actor.description|safe }}
                  </div>
                </div>
              </div>
            </div>
          </div>
    <section class="container_filmography">
      <div class="container_film_header filmography_header">
        Фильмография
      </div>
      <div class="container_film_item filmography_list">
        <div class="filmography_list_inner">
          <table class="filmography_table">
            <tr>
              <th>Год</th>
              <th>Название</th>
              <th>Роль</th>
            </tr>

                {% for movie in actor.film_director.all %}
            <tr>
                  <td class="first_column"> {{ movie.year }}</td>
                  <td class="second_column"><a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a></td>
                  <td class="third_column">Режиссер, Сценарист, Продюсер, Актер</td>
            </tr>
                {% endfor %}

          </table>
        </div>
      </div>
    </section>

  {% endblock movie %}

SN_Django/django_movie/templates/movies/base.html
{% extends 'base.html' %}
{% block title %}{% endblock title %}
  {% block content %}
    <main class="Content">
        <div class="Content_inner">
            {% include 'include/sidebar.html' %}
            {% block movie %}

            {% endblock movie %}
        </div>
    </main>
{% endblock content %}

SN_Django/django_movie/templates/movies/base_without_sidebar.html
{% extends 'base.html' %}
{% block title %}{% endblock title %}
  {% block content %}
    <main class="Content">
        <div class="Content_inner">
            {% block movie %}

            {% endblock movie %}
        </div>
    </main>
{% endblock content %}

SN_Django/django_movie/templates/movies/gallery.html
{% extends 'movies/base_without_sidebar.html' %}
{% block title %} Кадры из фильма {{ movie.title }} {% endblock title %}
  {% block movie %}
  <!-- The Modal -->
  <div id="modalPic" class="modal">
    <div class="modal_content_pic">
        <button class="btn_close" type="button">
        </button>
        <!-- <span class="btn_close">&times;</span> -->
        <img class="modal_pic" src="" alt=""/>
    </div>
  </div>

  <div class="container_film_header">
    <div class="container_film_header_text">Кадры из фильма "{{movie.title}}"</div>
  </div>
  <div class="container_films">
    <div class="container_film_item">
      <div class="container_film_item_inner">
          <a class="back_to back_to_detail" href="{{ movie.get_absolute_url }}">Назад</a>
          <div class="film_gallery">
              {% for image in movie.movieshots_set.all %}
                <img id="clickPic" class="film_pic" src="{{ image.image.url }}" alt="{{ image.description }}"/>
              {% endfor %}
          </div>
      </div>
    </div>
  </div>
  {% endblock movie %}


  

SN_Django/django_movie/templates/movies/list_movie.html
{% extends 'movies/base.html' %}
{% block title %} Список фильмов {% endblock title %}
 {% block movie %}
      <!-- Content -->
          <div class="container_film_header">
            <div class="container_film_header_text">Список фильмов</div>
          </div>
          <div class="search">
              {% include 'include/search.html' %}
          </div>
          <section class="movie_list">
              {% if not movie_list %}
                    <div class="not_found_movies">
                        <h2>Ничего не найдено</h2>
                    </div>
              {% endif %}
            {% for movie in movie_list %}
           <div class="movie_item">
             <div class="poster">
               <img src="{{ movie.poster.url }}">
             </div>
             <div class="info">
               <div class="title">
                 <h2>
                   <a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a>
                 </h2>
                </div>
               <div class="detail_info">
                 <ul class="info_list">
                    {% for genre in movie.genres.all %}
                   <li>Жанр: {{ genre.name }}</li>
                    {% endfor %}
                   <li>Продолжительность: {{ movie.runtime }} мин.</li>
                   <li>Год: {{ movie.year }}</li>
                 </ul>
                 <div class="rating">Средняя Оценка {{ movie.get_average_rating }}/10</div>
               </div>
             </div>
             <div class="buttons"><button class="add-to-list">Добавить в список</button></div>
           </div>
            {% endfor %}
          </section>
          <div class="pagination">
              {% include 'include/pagination.html' %}
          </div>
{% endblock movie %}